#229 - Refactor all modules using .ixx and .cpp files - due to compiler cl1 internal error (cpp)
Completed; Tested.
Finally, does not solve the **cl1** compiler internal error C1001 when using c++20 modules jointly with OpenCV instantiation of class `cv::Mat`.